name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: check out repository
    
    - name: Install SDL2 and SDL2_ttf
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

    - run: |
        ./CMakeGCC.sh
        cd /bin/make
        make
        ./sobel.exe
