name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: check out repository
    - run: |
        ./CMakeGCC.sh
        make CMakeFile
        ./sobel.exe
